<script lang="ts">

    import {page} from "$app/stores";
    import Page from "$lib/components/complex/page.svelte";
    import {Input} from "$lib/components/ui/input";
    import {Badge} from "$lib/components/ui/badge";
    import {config} from "../../config/shared";
    import type {Session} from "@auth/core/types";
    import * as Avatar from "$lib/components/ui/avatar";
    import * as Card from "$lib/components/ui/card";

    const landscape = config.app.landscape;

    const empty = $page.data.session?.user == null;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const session: Session | any = $page.data.session;


</script>

<Page notFoundMessage="User not found" {empty}>
    <div class="border-b border-b-muted">
        <h2 class="py-10 text-3xl lg:text-4xl text-foreground max-w-[1200px] w-11/12 mx-auto">
            Profile
        </h2>
    </div>
    <div class="w-full bg-muted dark:bg-background">
        <div class="max-w-[1200px] w-11/12 mx-auto grid gap-y-8 py-8 ">
            <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                <Card.Header>
                    <Card.Title>Username</Card.Title>
                </Card.Header>
                <Card.Content>
                    <Card.Description>This is a unique identifier for you. All your templates with prefix with this
                        value.
                    </Card.Description>
                    <Card.Description>This value cannot be changed.</Card.Description>
                    <Input disabled class="my-4" value="{$page.data.user.principal.username}"/>
                </Card.Content>
                <Card.Footer class="bg-muted rounded-b-lg p-4">
                    <Card.Description>This value is lowercase alphanumeric or -.</Card.Description>
                </Card.Footer>
            </Card.Root>
            <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                <Card.Header>
                    <Card.Title>Name</Card.Title>
                </Card.Header>
                <Card.Content>
                    <Card.Description>This is the name you signed up with</Card.Description>
                    <Input disabled class="my-4" value="{$page.data.session?.user?.name}"/>
                </Card.Content>
                <Card.Footer class="bg-muted rounded-b-lg p-4">
                    <Card.Description>There is no restriction to this name. However, changing it is not supported yet
                    </Card.Description>
                </Card.Footer>
            </Card.Root>
            <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                <Card.Header>
                    <Card.Title>User ID</Card.Title>
                </Card.Header>
                <Card.Content>
                    <Card.Description>Unique index for your user.</Card.Description>
                    <Input disabled class="my-4" value="{$page.data.user.principal.id}"/>
                </Card.Content>
                <Card.Footer class="bg-muted rounded-b-lg p-4">
                    <Card.Description>This is automated generated by your OAuth provider
                    </Card.Description>
                </Card.Footer>
            </Card.Root>

            <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                <div class="flex justify-between">
                    <div>
                        <Card.Header>
                            <Card.Title>Avatar</Card.Title>
                        </Card.Header>
                        <Card.Content>
                            <Card.Description>This is your profile picture</Card.Description>
                        </Card.Content>
                    </div>
                    <Avatar.Root class="h-20 w-20 m-8">
                        <Avatar.Image src="{session?.user?.image}"
                                      alt="@session?.user?.name}"/>
                        <Avatar.Fallback>{session?.user?.name?.slice(0, 2)?.toUpperCase()}</Avatar.Fallback>
                    </Avatar.Root>

                </div>
                <Card.Footer class="bg-muted rounded-b-lg p-4">
                    <Card.Description>This is obtained directly from your login method</Card.Description>
                </Card.Footer>
            </Card.Root>
            <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                <Card.Header>
                    <Card.Title>Email</Card.Title>
                </Card.Header>
                <Card.Content>
                    <Card.Description>This is the email associated with your sign up</Card.Description>
                    <Input disabled class="my-4" value="{session?.user?.email}"/>
                </Card.Content>
                <Card.Footer class="bg-muted rounded-b-lg p-4">
                    <Card.Description>This is associated with your login method</Card.Description>
                </Card.Footer>
            </Card.Root>

            {#if session?.roles?.length > 0}
                <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                    <Card.Header>
                        <Card.Title>Roles</Card.Title>
                    </Card.Header>
                    <Card.Content>
                        <Card.Description>The roles you are assigned</Card.Description>
                        <div>
                            {#each session?.roles as role}
                                <Badge>{role}</Badge>
                            {/each}
                        </div>
                    </Card.Content>
                    <Card.Footer class="bg-muted rounded-b-lg p-4">
                        <Card.Description>This is managed by CyanPrint registry administrators.</Card.Description>
                    </Card.Footer>
                </Card.Root>
            {/if}

            {#if session?.roles?.length > 0}
                <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                    <Card.Header>
                        <Card.Title>Permissions</Card.Title>
                    </Card.Header>
                    <Card.Content>
                        <Card.Description>The permissions associated with your account</Card.Description>
                        <div>
                            {#each session?.permissions as p}
                                <Badge>{p}</Badge>
                            {/each}
                        </div>
                    </Card.Content>
                    <Card.Footer class="bg-muted rounded-b-lg p-4">
                        <Card.Description>This is managed by CyanPrint registry administrators.</Card.Description>
                    </Card.Footer>
                </Card.Root>
            {/if}
            {#if landscape === "lapras" }
                <Card.Root class="shadow-xl dark:border-muted-foreground dark:bg-background">
                    <Card.Header>
                        <Card.Title>JWT Token</Card.Title>
                    </Card.Header>
                    <Card.Content>
                        <Card.Description>Access Token for development
                        </Card.Description>
                        <p style="text-wrap: wrap" class="max-w-[480px]">
                            {session?.access_token}
                        </p>
                    </Card.Content>
                    <Card.Footer class="bg-muted rounded-b-lg p-4">
                    </Card.Footer>
                </Card.Root>
            {/if}

        </div>
    </div>


</Page>
